# Content configuration version
version: 2

# Personal info
name: Vlad Dulgheru
title: Fullstack Software Engineer
email: dulgheruvladut@gmail.com
phone: +40753936574
website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: dulgheruvlad

# About Section
about_profile_image: profile.jpg
about_content: |
  Fullstack Software Engineer with 6+ years of experience building scalable, high-performance systems in telecom and enterprise environments. Strong backend expertise in Java, Spring Boot, and PostgreSQL, with practical frontend and DevOps knowledge. Proven track record in leading projects, mentoring developers, and improving system performance and code quality. Focused, adaptable, and passionate about clean architecture and continuous improvement.

content:
#  - title: Projects
#    layout: list
#    content: []

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Ceragon Networks
        sub_title: Java Technical Lead
        caption: Jul 2021 - Present (3 years and 10 months)
        link:
        quote: >
          Research & Development | Fullstack Telecom Software Solutions
        description: |
          * Led architectural design and sprint planning for a team of 3 engineers, aligning technical implementation with business requirements and agile practices.
          * Boosted system performance by 15% through backend bottleneck resolution and front-end rendering optimizations.
          * Increased system resilience and security by spearheading proactive refactoring, rigorous unit testing, and regular upgrade cycles.
          * Mentored junior developers via pair programming, documentation, and internal workshops, shortening onboarding time and raising team maturity.
          * Built and maintained distributed system components using Java, Spring Boot, PostgreSQL, Elasticsearch, and RESTful APIs.
          * Managed the CI/CD migration and implemented observability improvements using TeamCity, Kibana, Dynatrace, and Kafka, ensuring zero downtime and real-time alerting.

      - layout: left
        title: Ceragon Networks
        sub_title: Java Developer
        caption: Oct 2018 - Jul 2021 (2 years and 9 months)
        description: |
          * Delivered over 10 core features for a telecommunications platform using Java, JPA, and PostgreSQL.
          * Optimized backend logic and database queries, improving latency and overall system throughput by 25%.
          * Diagnosed and fixed 50+ production bugs across frontend/backend modules, contributing to system reliability.
          * Participated in UI/UX discussions and implemented JSON/XML APIs to improve client-side interactions.
          * Delivered POCs, code reviews, and feature estimations that contributed to improved sprint predictability.

      - layout: left
        title: Know How S.R.L
        sub_title: ERP Developer
        caption: Nov 2015 - Aug 2018 (2 years and 10 months)
        description: |
          * Developed and customized ERP workflows using Infor technologies (BaaN4, LN, ION), including front-end forms and back-end integration logic.

      - layout: left
        title: Pair Opportunities Commission of Veneto
        sub_title: Web Developer
        caption: Sep 2014 - Mar 2015 (7 months)
        description: |
          * Designed and launched a responsive website to promote computer science careers to women.
          * Integrated front-end UI with dynamic HTML/CSS/JS components under academic guidance.

      - layout: left
        title: StudioManoLibera
        sub_title: Graphic Designer (Collaboration)
        caption: Apr 2010 - May 2010 (2 months)
        description: |
          * Contributed digital artwork and visual assets for an Italian cartoon production using Adobe Suite tools.

      - layout: left
        title: CosmoFoto
        sub_title: Intern
        caption: Feb 2009 - Feb 2009 (1 month)
        description: |
          * Assisted with photo development and gained Photoshop experience in a production setting.

      - layout: left
        title: Municipality of Oderzo
        sub_title: Translator
        caption: Mar 2008 - Mar 2008 (1 month)
        description: |
          * Participated in a cultural translation initiative for the “Letters from the West” social services project.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Universitá Ca’Foscari Venezia
        sub_title: Bachelor's degree in Computer Science
        caption: 2013 - 2018
        description: |
          * Department of Environmental Sciences, Computer Science and Statistics

      - layout: top-left
        title: A.V. Obici
        sub_title: High School / Vocational School - Graphic Designer
        caption: 2007 - 2011
        description: |
          * Advertising Graphic Diploma
          * Trained in digital illustration and layout design

  - title: Skills
    layout: text
    content: |
      **Fullstack Technologies:**
      Java, Spring Boot, JPA, PostgreSQL, Hibernate, REST APIs, Elasticsearch, Kafka, HTML, CSS, JavaScript

      **DevOps & Observability:**
      CI/CD, Dynatrace, TeamCity, Kibana, Logstash, Log4j2, SNMP, NETCONF

      **Development Practices:**
      Agile Methodology, Pair Programming, Technical Documentation, System Design, Unit Testing, Code Reviews

      **Tools & Platforms:**
      Eclipse IDE, Maven, Unix/Linux, Microsoft Office, Adobe Photoshop, Adobe Illustrator

      **ERP & Legacy Systems:**
      BaaN IV, ERP Infor LN, F#, ION, XML, XSD, ER Studio

      **Soft Skills:**
      Mentoring, Communication, Team Collaboration, Requirements Analysis

      **Languages:**
      Italian: Advanced
      English: Intermediate

# Footer
footer_show_references: true

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
