# Site
# repository: sproogen/modern-resume-theme

# Content configuration version
version: 2

# Personal info
name: Vlad Dulgheru
title: Technical Lead - Ceragon Networks
email: dulgheruvladut@gmail.com
phone: +40753936574
website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: dulgheruvlad

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Highly motivated and results-driven Senior Software Engineer with 6+ years of experience in designing,
  developing, and implementing complex telecommunications solutions. Proven ability to lead technical
  discussions, mentor junior engineers. Adept at optimizing performance, ensuring code quality, and delivering
  high-impact features within agile environments.

content:
  - title: Projects
    layout: list
    content: []

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Ceragon Networks
        sub_title: Technical Lead
        caption: Jul 2021 - Present (3 years and 10 months)
        link:
        quote: >
          Research & Development | IT / Telecom
        description: |
          * Led architectural design and technical breakdown sessions for a team of 3 engineers, ensuring alignment with critical project goals and best practices, resulting in a 15% reduction in design flaws and improved team efficiency.
          * Drove a 15% improvement in system performance by identifying and resolving critical bottlenecks within the data processing pipeline, significantly reducing latency and enhancing user experience.
          * Reduced software vulnerabilities by 20% by leading proactive software upgrades and refactoring initiatives, coupled with the implementation of rigorous unit testing, thereby strengthening system security and stability.
          * Mentored and guided junior developers, fostering a collaborative environment and promoting knowledge sharing through regular tech talks and comprehensive documentation, leading to increased team cohesion and accelerated onboarding of new members.
          * Developed and maintained key system components using Java, Spring, and Elasticsearch, ensuring high availability and scalability to support a growing user base and critical business operations.
          * Led the migration of the CI/CD infrastructure, ensuring zero downtime during the transition, minimizing disruption to development workflows and maintaining continuous delivery of software releases.

      - layout: left
        title: Ceragon Networks
        sub_title: Java Developer
        caption: Oct 2018 - Present (6 years and 7 months)
        description: |
          * Designed, developed, and implemented 10+ features for the core telecommunications platform using Java, JPA, and PostgreSQL, enhancing system functionality.
          * Improved feature performance by 25% through code optimization and database query tuning, reducing latency and increasing throughput.
          * Successfully resolved 50+ high-priority bugs, ensuring system stability and reliability and minimizing downtime.
          * Conducted technical requirement reviews and developed proof-of-concepts for new features, contributing to effective project planning and reducing development time by 5%.
          * Collaborated with cross-functional teams (QA, Product) to deliver high-quality software solutions within tight deadlines.

      - layout: left
        title: Know How S.R.L
        sub_title: Developer
        caption: Nov 2015 - Aug 2018 (2 years and 10 months)
        description: |
          * Customization experience on ERP software, both technical and functional flows, for Infor products as BaaN4, LN, ION, SupplierWeb.

      - layout: left
        title: Pair Opportunities Commission of Veneto
        sub_title: Web Developer
        caption: Sep 2014 - Mar 2015 (7 months)
        description: |
          * Designed and developed a website aimed at introducing women to the field of computer science, under the supervision of Prof. Agostino Cortesi.

      - layout: left
        title: StudioManoLibera
        sub_title: Graphic Designer (Collaboration)
        caption: Apr 2010 - May 2010 (2 months)
        description: |
          * Contributed to the production of an animated video for a well-known Italian cartoon character.
          * Improved proficiency in Adobe Photoshop and Illustrator.

      - layout: left
        title: CosmoFoto
        sub_title: Intern
        caption: Feb 2009 - Feb 2009 (1 month)
        description: |
          * Worked on photo development and printing.
          * Improved skills in Adobe Photoshop.

      - layout: left
        title: Municipality of Oderzo
        sub_title: Translator
        caption: Mar 2008 - Mar 2008 (1 month)
        description: |
          * Participated in the "Letters from the West" project in collaboration with the Social Services office.
          * Gained experience working with multicultural teams.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Universitá Ca’Foscari Venezia
        sub_title: Bachelor's degree in Computer Science
        caption: 2013 - 2018
        quote: >
          Department of Environmental Sciences, Computer Science and Statistics

      - layout: top-right
        title: A.V. Obici
        sub_title: High School / Vocational School - Graphic Designer
        caption: 2007 - 2011
        description: |
          * Advertising Graphic Diploma
          * Learned and applied graphic-pictorial techniques for design and production

  - title: Skills
    layout: text
    content: |
      **Technical Skills:**
      Java, Spring, JPA, PostgreSQL, Hibernate, Elasticsearch, Kafka, Dynatrace, TeamCity, Kibana, Logstash, Log4j2, CI/CD, Agile Methodology, Eclipse IDE, Maven, SNMP, NETCONF

      **Other Technologies:**
      Adobe Photoshop, Adobe Illustrator, Corel Draw, HTML/CSS, JavaScript, SQL, Unix, XML, XSD, Microsoft Office, ER Studio, BaaN IV, ERP Infor LN, F#, ION

      **Soft Skills:**
      Mentoring, Communication, Teamwork, Project Planning, Documentation

      **Languages:**
      Italian: Advanced
      English: Intermediate

# Footer
footer_show_references: true

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
